### ISSUE TITLE
Error in the code?

### ISSUE THREAD

**Issue by AzaPattaz** [milaq/rpi-rf#34] opened 2018-08-31 16:49 UTC
Im trying to run the receive code with the exact arguments as this video https://www.youtube.com/watch?v=Xe5Bj_N4Crw however it is coming up with an error saying too many arguments are given.
![image](https://user-images.githubusercontent.com/19674707/44925363-2717fe80-ad46-11e8-8db1-6778ea5ec1ff.png)

I tried taking the main bit of code out and substituting values in and the same error occurred 
![image](https://user-images.githubusercontent.com/19674707/44925706-013f2980-ad47-11e8-85e7-2d4b6f5841fe.png)

**Comment by mferi87** [comment] 2018-09-13 18:54
Hi!
I have exactly this problem, is there any solution?
The receiver works just fine, but i can't send.
Thanks in advance!

**Comment by milaq** [comment] 2018-09-14 14:01
duplicate of #31

**Closed by milaq** 2018-09-14 14:01 UTC
